[tiny] Add post params to urid to support concurrent posts.
3rd-Eden/mana pull request #17
Opened 2019-10-15 19:22 UTC by fritzmonkey

2019-10-15 19:29 UTC, jcrugzz commented on index.js
> +    this.all(args.str + ':' + JSON.stringify(options.json)) :
my only thought around this is should it be hashed due to possible sensitive data? otherwise this seems reasonable. is options.json the only parameter that the body content can come through as?

2019-10-15 19:36 UTC, fritzmonkey commented on index.js
> +    this.all(args.str + ':' + JSON.stringify(options.json)) :
I thought about hashing as well, but it didn't seem worth it to bring in another dependency. This will be stored in memory as the queue key, and potentially logged via diagnostic, but that was happening previously, so this isn't really exposing anything new. The params initially come in as `args.options.params`, but are then built to `options.json` for non-GET requests.

2019-10-15 19:54 UTC, jcrugzz approved these changes

2019-10-15 20:10 UTC, msluther requested changes
IMHO it should be a more holistic change and not _just_ about POST.

2019-10-15 20:10 UTC, msluther commented on index.js
> +      this.push(args.str + ':' + JSON.stringify(options.json), args.fn);
can we only stringify once?

2019-10-15 20:10 UTC, msluther commented on index.js
> +    } else if (options.method === 'POST') {
again, should this just check for a body rather than the http method?

2019-10-15 20:10 UTC, msluther commented on index.js
> +      this.push(args.str + ':' + JSON.stringify(options.json), args.fn);
or just creation of the whole string once

2019-10-15 20:10 UTC, msluther commented on index.js
> +    this.all(args.str + ':' + JSON.stringify(options.json)) :
They're not there indefinitely though in memory, just while the request is happening right? And diagnostics is entirely on the consumer, if you don't want your sensitive data logged, be careful with turning on diagnostics.  e.g. you could also very well embed credentials in plaintext in the url `http://foo:bar@example.com` If you don't want the urls logged, don't turn on diagnostics for the the package that is handling your urls.

2019-10-15 23:05 UTC, msluther approved these changes

2019-10-16 13:16 UTC, 3rd-Eden approved these changes

2019-10-16 13:16 UTC, merged

2019-10-16 13:28 UTC, 3rd-Eden commented
Released as 1.1.0